/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Piece;
import tp5client.Traitement;

/**
 *
 * @author Erwan
 */
public class Pieces extends javax.swing.JPanel {

    /**
     * Creates new form Pieces
     */
    Traitement traitement;
    int tailleCompteur = 10;
    Piece pieceSelected;
    int nombreSelected;

    public Pieces(Traitement traitement) {
        initComponents();
        initCompteur();

        this.traitement = traitement;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listeName = new javax.swing.JComboBox();
        number = new javax.swing.JComboBox();
        confirmation = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(148, 208, 228));

        jLabel1.setFont(new java.awt.Font("13_Misa", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Choisir votre piece");

        listeName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 - Selection Pieces" }));
        listeName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listeNameItemStateChanged(evt);
            }
        });
        listeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeNameActionPerformed(evt);
            }
        });

        number.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        number.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                numberItemStateChanged(evt);
            }
        });

        confirmation.setText("Confirmation");
        confirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(listeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationActionPerformed
        try {
            // TODO add your handling code here:
//        System.out.println(evt.getActionCommand());
            traitement.newReservation(pieceSelected, nombreSelected);
        } catch (IOException ex) {
            Logger.getLogger(Pieces.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmationActionPerformed

    private void listeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeNameActionPerformed
        // TODO add your handling code here:
//        System.out.println(evt.getActionCommand());
//        System.out.println(evt.getItem());
    }//GEN-LAST:event_listeNameActionPerformed

    private void listeNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listeNameItemStateChanged
        // TODO add your handling code here:
//        System.out.println("--------------");
//        System.out.println(evt.getItem());
        pieceSelected = traitement.choixPieces(evt.getItem());
//        String[] splitArray = null;
//        splitArray = evt.getItem().toString().split("-");
//        System.out.println(parseInt(splitArray[0])); 
////        this.piece = (Piece) evt.getItem();
//        System.out.println(this.piece.nom);
//        System.out.println(evt.getItemSelectable());
//        System.out.println(evt.paramString());
//        System.out.println(evt.getID());
//        System.out.println(evt.getStateChange());

    }//GEN-LAST:event_listeNameItemStateChanged

    private void numberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_numberItemStateChanged
        try {
            nombreSelected = Integer.parseInt(evt.getItem().toString());
        } catch (NumberFormatException nfe) {}
    }//GEN-LAST:event_numberItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox listeName;
    private javax.swing.JComboBox number;
    // End of variables declaration//GEN-END:variables

    void initPieces(model.Pieces pieces) {

        listeName.removeAllItems();
        for (int i = 0; i < pieces.listePieces.size(); i++) {
            if (pieces.listePieces.get(i).placeDispo != 0) {
//                listeName.addItem(i + " - " + pieces.listePieces.get(i).nom + " - Place disponoble : " + pieces.listePieces.get(i).placeDispo);
                listeName.addItem(pieces.listePieces.get(i).toString());

            }
        }
    }

    private void initCompteur() {
        number.removeAllItems();
        for (int i = 1; i <= tailleCompteur; i++) {
            number.addItem(i);
        }
    }
}
